#!name=Duolingo Max 解锁
#!desc=解锁 Duolingo Max 会员
#!author=Takagivegeta

[Script]
max = type=http-response, pattern=^https?://(ios-api-[a-z0-9-]+|api\d+)\.duolingo\.c(n|om)/2023-05-23/batch, script-path=https://raw.githubusercontent.com/waterdrops/MyScripts/refs/heads/develop/lingoDuo/lingoDuo-xaM.js, requires-body=1, max-size=31457280, timeout=120
all_feats = type=http-response, pattern=^https?://(ios-api-[a-z0-9-]+|api\d+)\.duolingo\.c(n|om)/2023-05-23/users/.+/available-features, script-path=https://raw.githubusercontent.com/waterdrops/MyScripts/refs/heads/develop/lingoDuo/lingoDuo-feats.js, requires-body=1, timeout=120
live_challenge = type=http-response, pattern=^https?://(ios-api-[a-z0-9-]+|api\d+)\.duolingo\.c(n|om)/2023-05-23/users\/.+/live-ops-challenges, script-path=https://raw.githubusercontent.com/waterdrops/MyScripts/refs/heads/develop/lingoDuo/lingoDuo-time-modifier.js, requires-body=1, timeout=120

[MITM]
hostname = %APPEND% ios-api-*.duolingo.com, ios-api-*.duolingo.cn, api*.duolingo.com, api*.duolingo.cn
